# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62cadd91534c227ae75c2ee8a072010174a41c399068e24e1d19d0b430d639360f0c41a0be290ea0a8a092a04eddaf4a8cffb8e459f646fac18467a20714e2e9

test:
  secret_key_base: 4e38b05a6a10d6c995a4f3d95fc52cdc9d65664c83df355e667776623e58893547ba1b51152fce2fe0c82232809868d96508b772eb4e135e31116c741ee08aae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
